'use client'

import { createContext, useContext, useState } from 'react'
import { useDashboardState } from '../hooks/useDashboardState'

const DashboardContext = createContext(null)

export function DashboardProvider({ children }) {
    const [viewMode, setViewMode] = useState('Y')

    const dashboardState = useDashboardState(viewMode)

    const value = {
        viewMode,
        setViewMode,
        ...dashboardState
    }

    return (
        <DashboardContext.Provider value={value}>
            {children}
        </DashboardContext.Provider>
    )
}

export function useDashboard() {
    const context = useContext(DashboardContext)
    if (!context) {
        // Return empty state during prerendering - components should handle this gracefully
        return {
            viewMode: 'Y',
            setViewMode: () => {},
            appState: {
                calculations: [],
                modules: [],
                inputGlass: [],
                inputGlassGroups: [],
                inputGlassArrays: {},
                keyPeriods: [],
                indices: [],
                config: {}
            },
            setters: {},
            derived: {
                timeline: { periods: 0, labels: [] },
                autoGeneratedFlags: {},
                autoGeneratedIndexations: {},
                referenceMap: {},
                calculationResults: {},
                calculationErrors: {}
            },
            uiState: {},
            handlers: {}
        }
    }
    return context
}
