'use client'

import { useState } from 'react'
import { Hexagon, Settings } from 'lucide-react'
import { usePathname } from 'next/navigation'
import { useDashboard } from '../context/DashboardContext'
import DashboardNavigation from './DashboardNavigation'
import ConfigPanel from '@/components/inputs/ConfigPanel'
import SettingsModal from '@/components/inputs/SettingsModal'

export default function DashboardShell({ children }) {
    const pathname = usePathname()
    const [showSettings, setShowSettings] = useState(false)
    const {
        viewMode,
        setViewMode,
        inputsEditMode,
        setInputsEditMode,
        appState,
        setters,
        derived
    } = useDashboard()

    const {
        showConfig,
        config,
        inputGlass
    } = appState

    const {
        setConfig
    } = setters

    const {
        timeline,
        autoGeneratedFlags,
        autoGeneratedIndexations
    } = derived

    // Determine if we should show the config panel based on route
    const showConfigPanel = showConfig && (
        pathname === '/dashboard/inputs' ||
        pathname === '/dashboard/key-periods' ||
        pathname === '/dashboard/modules' ||
        pathname === '/dashboard/calculations'
    )

    return (
        <div className="min-h-screen bg-slate-50">
            {/* Sticky Header Container - includes header, nav, and config panel */}
            <div className="sticky top-0 z-50">
                {/* Main Header */}
                <header className="bg-white border-b border-slate-200 shadow-sm">
                    <div className="max-w-[1800px] mx-auto px-6 py-3">
                        <div className="flex items-center justify-between">
                            {/* Left: Logo and Title */}
                            <div className="flex items-center gap-4">
                                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center">
                                    <Hexagon className="w-5 h-5 text-white" />
                                </div>
                                <div>
                                    <h1 className="text-lg font-bold text-slate-900">Glass Inputs</h1>
                                    <p className="text-xs text-slate-500">Financial Model Builder</p>
                                </div>
                            </div>

                            {/* Right: Toggles and Settings */}
                            <div className="flex items-center gap-4">
                                {/* View Mode Selector */}
                                <div className="flex items-center gap-3">
                                    <span className="text-xs text-slate-500">View:</span>
                                    <div className="flex bg-slate-100 p-1 rounded-lg border border-slate-200">
                                        {['M', 'Q', 'Y', 'FY'].map(mode => (
                                            <button
                                                key={mode}
                                                onClick={() => setViewMode(mode)}
                                                className={`px-3 py-1.5 rounded-md text-sm font-semibold transition-all ${
                                                    viewMode === mode
                                                        ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-500/25'
                                                        : 'text-slate-600 hover:text-slate-900 hover:bg-slate-200'
                                                }`}
                                            >
                                                {mode}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                                <button
                                    onClick={() => setShowSettings(true)}
                                    className="p-2 text-slate-500 hover:text-slate-700 hover:bg-slate-100 rounded-lg transition-colors"
                                    title="Settings"
                                >
                                    <Settings className="w-5 h-5" />
                                </button>
                            </div>
                        </div>
                    </div>
                </header>

                {/* Navigation Bar */}
                <DashboardNavigation />

                {/* Config Panel - only show on inputs and key-periods pages */}
                {showConfigPanel && (
                    <ConfigPanel
                        config={config}
                        setConfig={setConfig}
                        timeline={timeline}
                        inputCount={inputGlass.length}
                        flagCount={Object.keys(autoGeneratedFlags).length}
                        indexCount={Object.keys(autoGeneratedIndexations).length}
                        inputsEditMode={inputsEditMode}
                        setInputsEditMode={setInputsEditMode}
                    />
                )}
            </div>

            {/* Page Content */}
            <main className="text-slate-900">
                {children}
            </main>

            {/* Settings Modal */}
            <SettingsModal
                isOpen={showSettings}
                onClose={() => setShowSettings(false)}
                config={config}
                setConfig={setConfig}
            />
        </div>
    )
}
