'use client'

import { TAB_CONFIG } from './tabs'
import { useDashboardState } from '../hooks/useDashboardState'
import DashboardHeader from './DashboardHeader'
import ConfigPanel from '@/components/inputs/ConfigPanel'

export default function DashboardContent({ viewMode, setViewMode }) {
    const {
        appState,
        setters,
        derived,
        handlers,
        autoSaveState,
        uiState
    } = useDashboardState(viewMode)

    const {
        activeTab,
        showConfig,
        config,
        keyPeriods,
        inputGlass
    } = appState

    const {
        setActiveTab,
        setShowConfig,
        setConfig
    } = setters

    const {
        timeline,
        autoGeneratedFlags,
        autoGeneratedIndexations
    } = derived

    const {
        handleRevertToOriginal
    } = handlers

    const {
        saveStatus
    } = autoSaveState

    // Find the active tab's component
    const activeTabConfig = TAB_CONFIG.find(t => t.id === activeTab)
    const ActiveTabComponent = activeTabConfig?.Component

    return (
        <div className="text-slate-900">
            {/* Sub-header with internal tabs and actions */}
            <DashboardHeader
                tabs={TAB_CONFIG}
                activeTab={activeTab}
                onTabChange={setActiveTab}
                timeline={timeline}
                showConfig={showConfig}
                onToggleConfig={() => setShowConfig(!showConfig)}
                saveStatus={saveStatus}
                onRevertToOriginal={handleRevertToOriginal}
            />

            {/* Config Panel - only show on inputs and keyPeriods tabs */}
            {showConfig && (activeTab === 'inputs' || activeTab === 'keyPeriods') && (
                <ConfigPanel
                    config={config}
                    setConfig={setConfig}
                    timeline={timeline}
                    inputCount={inputGlass.length}
                    flagCount={Object.keys(autoGeneratedFlags).length}
                    indexCount={Object.keys(autoGeneratedIndexations).length}
                />
            )}

            {/* Tab Content */}
            {ActiveTabComponent && (
                <ActiveTabComponent
                    appState={appState}
                    setters={setters}
                    derived={derived}
                    handlers={handlers}
                    uiState={uiState}
                    viewMode={viewMode}
                    config={config}
                    keyPeriods={keyPeriods}
                />
            )}
        </div>
    )
}
