'use client'

import React from 'react'
import { Plus, Trash2, GripVertical, ChevronDown, ChevronRight, FolderPlus } from 'lucide-react'
import { useDashboard } from '../context/DashboardContext'
import { getAggregatedValueForArray } from '@/utils/valueAggregation'
import { groupInputsBySubgroup } from '@/components/inputs/utils/inputHelpers'

export default function CalculationsPage() {
    const {
        viewMode,
        appState,
        setters,
        derived,
        uiState,
        handlers
    } = useDashboard()

    const {
        calculations,
        calculationsTabs,
        calculationsGroups,
        collapsedCalculationsGroups,
        modules,
        inputGlass,
        inputGlassGroups
    } = appState

    const { setAppState, setSelectedCalculationId, setCollapsedCalculationsGroups, setCalculationsTabs } = setters

    // Tab state - active tab
    const [activeTabId, setActiveTabId] = React.useState(() => {
        const tabs = calculationsTabs || []
        return tabs.length > 0 ? tabs[0].id : null
    })

    const {
        timeline,
        viewHeaders,
        referenceMap,
        calculationResults,
        calculationErrors,
        calculationTypes,
        autoGeneratedFlags,
        autoGeneratedIndexations,
        expandFormulaToNames
    } = derived

    const {
        selectedCalculationId,
        calcDraggedIndex,
        calcDragOverIndex
    } = uiState

    const {
        handleCalcDragStart,
        handleCalcDragOver,
        handleCalcDrop,
        handleCalcDragEnd
    } = handlers

    // Tab management functions
    const addTab = () => {
        const tabs = calculationsTabs || []
        const newId = tabs.length > 0 ? Math.max(...tabs.map(t => t.id)) + 1 : 1
        setAppState(prev => ({
            ...prev,
            calculationsTabs: [...(prev.calculationsTabs || []), {
                id: newId,
                name: `Sheet ${newId}`
            }]
        }))
        setActiveTabId(newId)
    }

    const updateTab = (tabId, name) => {
        setAppState(prev => ({
            ...prev,
            calculationsTabs: (prev.calculationsTabs || []).map(t =>
                t.id === tabId ? { ...t, name } : t
            )
        }))
    }

    const removeTab = (tabId) => {
        const tabs = calculationsTabs || []
        if (tabs.length <= 1) return // Don't allow removing the last tab

        const remainingTabs = tabs.filter(t => t.id !== tabId)
        const firstTabId = remainingTabs[0]?.id

        // Move calculations and groups from deleted tab to first remaining tab
        setAppState(prev => ({
            ...prev,
            calculationsTabs: remainingTabs,
            calculationsGroups: (prev.calculationsGroups || []).map(g =>
                g.tabId === tabId ? { ...g, tabId: firstTabId } : g
            ),
            calculations: (prev.calculations || []).map(c =>
                c.tabId === tabId ? { ...c, tabId: firstTabId } : c
            )
        }))

        if (activeTabId === tabId) {
            setActiveTabId(firstTabId)
        }
    }

    // Group management functions
    const addCalculationsGroup = () => {
        const groups = calculationsGroups || []
        const newId = groups.length > 0 ? Math.max(...groups.map(g => g.id)) + 1 : 1
        setAppState(prev => ({
            ...prev,
            calculationsGroups: [...(prev.calculationsGroups || []), {
                id: newId,
                tabId: activeTabId,
                name: `Group ${newId}`
            }]
        }))
    }

    const updateCalculationsGroup = (groupId, field, value) => {
        setAppState(prev => ({
            ...prev,
            calculationsGroups: (prev.calculationsGroups || []).map(g =>
                g.id === groupId ? { ...g, [field]: value } : g
            )
        }))
    }

    const removeCalculationsGroup = (groupId) => {
        // Move calculations to first remaining group or delete them
        const groups = calculationsGroups || []
        const remainingGroups = groups.filter(g => g.id !== groupId)
        const firstGroupId = remainingGroups.length > 0 ? remainingGroups[0].id : null

        setAppState(prev => ({
            ...prev,
            calculationsGroups: remainingGroups,
            calculations: firstGroupId
                ? (prev.calculations || []).map(c =>
                    c.groupId === groupId ? { ...c, groupId: firstGroupId } : c
                )
                : (prev.calculations || []).filter(c => c.groupId !== groupId)
        }))
    }

    const toggleGroupCollapse = (groupId) => {
        setCollapsedCalculationsGroups(prev => {
            const newSet = new Set(prev)
            if (newSet.has(groupId)) {
                newSet.delete(groupId)
            } else {
                newSet.add(groupId)
            }
            return newSet
        })
    }

    const addCalculation = (groupId = null) => {
        const tabGroups = (calculationsGroups || []).filter(g => g.tabId === activeTabId)
        const targetGroupId = groupId || (tabGroups.length > 0 ? tabGroups[0].id : null)

        // If no groups exist for this tab, create one first
        if (!targetGroupId) {
            const newGroupId = (calculationsGroups || []).length > 0
                ? Math.max(...(calculationsGroups || []).map(g => g.id)) + 1
                : 1
            setAppState(prev => ({
                ...prev,
                calculationsGroups: [...(prev.calculationsGroups || []), { id: newGroupId, tabId: activeTabId, name: 'Calculations' }],
                calculations: [...(prev.calculations || []), {
                    id: Date.now(),
                    tabId: activeTabId,
                    groupId: newGroupId,
                    name: 'New Calculation',
                    formula: '',
                    description: ''
                }]
            }))
            return
        }

        const newCalc = {
            id: Date.now(),
            tabId: activeTabId,
            groupId: targetGroupId,
            name: 'New Calculation',
            formula: '',
            description: ''
        }
        setAppState(prev => ({
            ...prev,
            calculations: [...(prev.calculations || []), newCalc]
        }))
    }

    const updateCalculation = (calcId, field, value) => {
        setAppState(prev => ({
            ...prev,
            calculations: prev.calculations.map(c =>
                c.id === calcId ? { ...c, [field]: value } : c
            )
        }))
    }

    const removeCalculation = (calcId) => {
        setAppState(prev => ({
            ...prev,
            calculations: prev.calculations.filter(c => c.id !== calcId)
        }))
    }

    // Build reference list for sidebar
    const buildReferenceList = () => {
        const activeGroups = inputGlassGroups.filter(group =>
            inputGlass.some(input => input.groupId === group.id)
        )
        const modeIndices = { values: 0, series: 0, constant: 0, timing: 0, lookup: 0 }

        return activeGroups.map(group => {
            const groupInputs = inputGlass.filter(input => input.groupId === group.id)

            // Determine group mode/type - check groupType first, then fall back to entryMode, then input mode
            let normalizedMode
            if (group.groupType === 'timing') {
                normalizedMode = 'timing'
            } else {
                const groupMode = group.entryMode || groupInputs[0]?.mode || 'values'
                // Normalize mode names
                if (groupMode === 'constants') normalizedMode = 'constant'
                else if (groupMode === 'lookup' || groupMode === 'lookup2') normalizedMode = 'lookup'
                else normalizedMode = groupMode
            }

            modeIndices[normalizedMode]++
            const modePrefix = normalizedMode === 'timing' ? 'T' :
                              normalizedMode === 'series' ? 'S' :
                              normalizedMode === 'constant' ? 'C' :
                              normalizedMode === 'lookup' ? 'L' : 'V'
            const groupRef = `${modePrefix}${modeIndices[normalizedMode]}`

            return {
                group,
                groupRef,
                normalizedMode,
                groupInputs
            }
        })
    }

    const referenceList = buildReferenceList()

    // Build calculation index map for R references
    const calcIndexMap = new Map()
    let globalCalcIndex = 0
    ;(calculationsGroups || []).forEach(group => {
        const groupCalcs = (calculations || []).filter(c => c.groupId === group.id)
        groupCalcs.forEach(calc => {
            globalCalcIndex++
            calcIndexMap.set(calc.id, globalCalcIndex)
        })
    })
    // Also include ungrouped calculations
    ;(calculations || []).filter(c => !c.groupId || !(calculationsGroups || []).some(g => g.id === c.groupId)).forEach(calc => {
        globalCalcIndex++
        calcIndexMap.set(calc.id, globalCalcIndex)
    })

    return (
        <main className="max-w-[1800px] mx-auto px-6 py-6">
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
                {/* Calculations Header */}
                <div className="px-6 py-4 border-b border-slate-200 bg-slate-50">
                    <div className="flex items-center justify-between">
                        <div>
                            <h2 className="text-lg font-semibold text-slate-900">Calculations</h2>
                            <p className="text-sm text-slate-500">Build formulas using input references</p>
                            <div className="flex items-center gap-4 mt-2 text-xs text-slate-600">
                                <span className="font-medium text-slate-700">Syntax:</span>
                                <span><code className="bg-slate-200 px-1.5 py-0.5 rounded">V1 + S1</code> Addition</span>
                                <span><code className="bg-slate-200 px-1.5 py-0.5 rounded">V1 * F1</code> Multiply by flag</span>
                                <span><code className="bg-slate-200 px-1.5 py-0.5 rounded">C1 * T1.1</code> Stock × Timing = Flow</span>
                                <span><code className="bg-slate-200 px-1.5 py-0.5 rounded">R1 + R2</code> Chain calculations</span>
                            </div>
                        </div>
                        <div className="flex items-center gap-2">
                            <button
                                onClick={addCalculationsGroup}
                                className="flex items-center gap-2 px-3 py-2 text-slate-600 border border-slate-300 rounded-lg hover:bg-slate-100 transition-colors"
                            >
                                <FolderPlus className="w-4 h-4" />
                                Add Group
                            </button>
                            <button
                                onClick={() => addCalculation()}
                                className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"
                            >
                                <Plus className="w-4 h-4" />
                                Add Calculation
                            </button>
                        </div>
                    </div>
                </div>

                <div className="flex">
                    {/* Available References Panel */}
                    <div className="w-72 border-r border-slate-200 bg-slate-50 p-4">
                        <h3 className="text-sm font-semibold text-slate-700 mb-3">Available References</h3>

                        {/* Input Arrays (excluding timing and lookup - shown separately) */}
                        {referenceList.filter(r => r.normalizedMode !== 'timing' && r.normalizedMode !== 'lookup').map(({ group, groupRef, normalizedMode, groupInputs }) => (
                            <div key={group.id} className="mb-3">
                                <div className="flex items-center gap-2 mb-1">
                                    <span className={`text-xs px-1.5 py-0.5 rounded font-medium ${
                                        normalizedMode === 'timing'
                                            ? 'text-teal-600 bg-teal-100'
                                            : normalizedMode === 'series'
                                                ? 'text-green-600 bg-green-100'
                                                : normalizedMode === 'constant'
                                                    ? 'text-blue-600 bg-blue-100'
                                                    : 'text-purple-600 bg-purple-100'
                                    }`}>
                                        {groupRef}
                                    </span>
                                    <span className="text-xs font-medium text-slate-700">{group.name}</span>
                                </div>
                                <div className="pl-4 space-y-1">
                                    {groupInputs.map((input, idx) => (
                                        <div key={input.id} className="flex items-center gap-2 text-xs text-slate-600">
                                            <span className={`px-1 py-0.5 rounded ${
                                                normalizedMode === 'timing'
                                                    ? 'text-teal-600 bg-teal-50'
                                                    : normalizedMode === 'series'
                                                        ? 'text-green-600 bg-green-50'
                                                        : normalizedMode === 'constant'
                                                            ? 'text-blue-600 bg-blue-50'
                                                            : 'text-purple-600 bg-purple-50'
                                            }`}>
                                                {groupRef}.{idx + 1}
                                            </span>
                                            <span className="truncate">{input.name}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        ))}

                        {/* Flags */}
                        {Object.keys(autoGeneratedFlags).length > 0 && (
                            <div className="mb-3 pt-3 border-t border-slate-200">
                                <div className="text-xs font-semibold text-amber-600 mb-2">Flags</div>
                                <div className="space-y-1">
                                    {Object.values(autoGeneratedFlags).map((flag, idx) => (
                                        <div key={flag.id} className="flex items-center gap-2 text-xs text-slate-600">
                                            <span className="px-1 py-0.5 rounded text-amber-600 bg-amber-50">
                                                F{idx + 1}
                                            </span>
                                            <span className="truncate">{flag.name}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Indexations */}
                        {Object.keys(autoGeneratedIndexations).length > 0 && (
                            <div className="mb-3 pt-3 border-t border-slate-200">
                                <div className="text-xs font-semibold text-cyan-600 mb-2">Indexations</div>
                                <div className="space-y-1">
                                    {Object.values(autoGeneratedIndexations).map((idx, i) => (
                                        <div key={idx.id} className="flex items-center gap-2 text-xs text-slate-600">
                                            <span className="px-1 py-0.5 rounded text-cyan-600 bg-cyan-50">
                                                I{i + 1}
                                            </span>
                                            <span className="truncate">{idx.name}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Lookups */}
                        {(() => {
                            const lookupGroups = inputGlassGroups.filter(g => g.entryMode === 'lookup' || g.entryMode === 'lookup2')
                            if (lookupGroups.length === 0) return null

                            return (
                                <div className="mb-3 pt-3 border-t border-slate-200">
                                    <div className="text-xs font-semibold text-lime-600 mb-2">Lookups</div>
                                    <div className="space-y-3">
                                        {lookupGroups.map((group, groupIdx) => {
                                            const groupInputs = inputGlass.filter(input => input.groupId === group.id)
                                            const lookupRef = `L${groupIdx + 1}`
                                            const subgroups = group.subgroups || []
                                            const rootInputs = groupInputs.filter(inp => !inp.subgroupId)
                                            const hasActualSubgroups = subgroups.length > 0
                                            const selectedIndices = group.selectedIndices || {}

                                            return (
                                                <div key={group.id}>
                                                    {/* Group Header */}
                                                    <div className="flex items-center gap-2 text-xs text-slate-600 mb-1">
                                                        <span className="px-1 py-0.5 rounded text-lime-600 bg-lime-100 font-medium">
                                                            {lookupRef}
                                                        </span>
                                                        <span className="truncate font-medium">{group.name}</span>
                                                    </div>

                                                    {/* No subgroups: show inputs directly as L3.1, L3.2, etc. */}
                                                    {!hasActualSubgroups && (
                                                        <div className="pl-3 space-y-0.5">
                                                            {rootInputs.map((input, inputIdx) => {
                                                                const inputRef = `${lookupRef}.${inputIdx + 1}`
                                                                return (
                                                                    <div key={input.id} className="flex items-center gap-2 text-xs text-slate-500">
                                                                        <span className="px-1 py-0.5 rounded text-lime-500 bg-lime-50">
                                                                            {inputRef}
                                                                        </span>
                                                                        <span className="text-slate-400">{input.name}</span>
                                                                    </div>
                                                                )
                                                            })}
                                                        </div>
                                                    )}

                                                    {/* With subgroups: show L3.1 (subgroup), L3.1.1, L3.1.2 (options) */}
                                                    {hasActualSubgroups && (
                                                        <div className="pl-3 space-y-2">
                                                            {groupInputsBySubgroup(groupInputs, group).map((sg, sgIdx) => {
                                                                if (sg.inputs.length === 0) return null

                                                                const key = sg.id ?? 'root'
                                                                const hasSelection = selectedIndices[key] !== undefined
                                                                const selectedIdx = selectedIndices[key] ?? 0
                                                                const selectedInput = sg.inputs[selectedIdx] || sg.inputs[0]
                                                                const subgroupRef = `${lookupRef}.${sgIdx + 1}`

                                                                return (
                                                                    <div key={sg.id ?? 'root'}>
                                                                        {/* Selected value row */}
                                                                        <div className="flex items-center gap-2 text-xs mb-0.5">
                                                                            <span className={`px-1 py-0.5 rounded font-medium ${hasSelection ? 'text-amber-600 bg-amber-50' : 'text-lime-600 bg-lime-50'}`}>
                                                                                {subgroupRef}
                                                                            </span>
                                                                            {sg.name && (
                                                                                <span className="text-slate-500">{sg.name}:</span>
                                                                            )}
                                                                            <span className={hasSelection ? 'text-amber-700 font-medium' : 'text-slate-500'}>{selectedInput?.name}</span>
                                                                            {hasSelection && <span className="text-[10px] text-amber-500">● selected</span>}
                                                                        </div>
                                                                        {/* Individual options */}
                                                                        <div className="pl-4 space-y-0.5">
                                                                            {sg.inputs.map((input, inputIdx) => {
                                                                                const isSelected = hasSelection && inputIdx === selectedIdx
                                                                                const optionRef = `${subgroupRef}.${inputIdx + 1}`
                                                                                return (
                                                                                    <div key={input.id} className="flex items-center gap-2 text-xs text-slate-500">
                                                                                        <span className={`px-1 py-0.5 rounded ${isSelected ? 'text-amber-500 bg-amber-50/50' : 'text-lime-500 bg-lime-50'}`}>
                                                                                            {optionRef}
                                                                                        </span>
                                                                                        <span className="text-slate-400">{input.name}</span>
                                                                                        {isSelected && (
                                                                                            <span className="text-[10px] text-amber-400">●</span>
                                                                                        )}
                                                                                    </div>
                                                                                )
                                                                            })}
                                                                        </div>
                                                                    </div>
                                                                )
                                                            })}
                                                        </div>
                                                    )}
                                                </div>
                                            )
                                        })}
                                    </div>
                                </div>
                            )
                        })()}

                        {/* Time Constants */}
                        <div className="mb-3 pt-3 border-t border-slate-200">
                            <div className="text-xs font-semibold text-teal-600 mb-2">Time Constants</div>
                            <div className="space-y-0.5">
                                {[
                                    { ref: 'T.DiM', name: 'Days in Month', desc: '28-31' },
                                    { ref: 'T.DiY', name: 'Days in Year', desc: '365/366' },
                                    { ref: 'T.DiQ', name: 'Days in Quarter', desc: '~90-92' },
                                    { ref: 'T.MiY', name: 'Months in Year', desc: '12' },
                                    { ref: 'T.MiQ', name: 'Months in Quarter', desc: '3' },
                                    { ref: 'T.QiY', name: 'Quarters in Year', desc: '4' },
                                    { ref: 'T.WiY', name: 'Weeks in Year', desc: '52/53' },
                                    { ref: 'T.HiD', name: 'Hours in Day', desc: '24' },
                                    { ref: 'T.HiM', name: 'Hours in Month', desc: 'DiM×24' },
                                    { ref: 'T.HiY', name: 'Hours in Year', desc: '8760/8784' },
                                ].map(({ ref, name, desc }) => (
                                    <div key={ref} className="flex items-center gap-2 text-xs text-slate-600">
                                        <span className="px-1 py-0.5 rounded text-teal-600 bg-teal-50 font-mono text-[10px]">
                                            {ref}
                                        </span>
                                        <span className="truncate">{name}</span>
                                        <span className="text-slate-400 text-[10px]">({desc})</span>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Timing (user-defined flow converters) */}
                        {referenceList.filter(r => r.normalizedMode === 'timing').length > 0 && (
                            <div className="mb-3 pt-3 border-t border-slate-200">
                                <div className="text-xs font-semibold text-teal-600 mb-2">Timing (Custom)</div>
                                <div className="space-y-1">
                                    {referenceList.filter(r => r.normalizedMode === 'timing').map(({ groupRef, groupInputs }) => (
                                        groupInputs.map((input, idx) => (
                                            <div key={input.id} className="flex items-center gap-2 text-xs text-slate-600">
                                                <span className="px-1 py-0.5 rounded text-teal-600 bg-teal-50">
                                                    {groupRef}.{idx + 1}
                                                </span>
                                                <span className="truncate">{input.name}</span>
                                            </div>
                                        ))
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Modules */}
                        {modules && modules.length > 0 && (
                            <div className="mb-3 pt-3 border-t border-slate-200">
                                <div className="text-xs font-semibold text-orange-600 mb-2">Modules</div>
                                <div className="space-y-2">
                                    {modules.map((module, idx) => (
                                        <div key={module.id}>
                                            <div className="flex items-center gap-2 text-xs text-slate-600 mb-1">
                                                <span className="px-1 py-0.5 rounded text-orange-600 bg-orange-50 font-medium">
                                                    M{idx + 1}
                                                </span>
                                                <span className="truncate font-medium">{module.name}</span>
                                            </div>
                                            <div className="pl-4 space-y-0.5">
                                                {module.outputs && module.outputs.map((output, outputIdx) => (
                                                    <div key={output} className="flex items-center gap-2 text-xs text-slate-500">
                                                        <span className="px-1 py-0.5 rounded text-orange-500 bg-orange-50">
                                                            M{idx + 1}.{outputIdx + 1}
                                                        </span>
                                                        <span className="text-slate-400">{output.replace(/_/g, ' ')}</span>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Calculations List - Grouped */}
                    <div className="flex-1 flex flex-col">
                        {/* Tab Bar */}
                        <div className="px-4 py-2 border-b border-slate-200 bg-white flex items-center gap-1 overflow-x-auto">
                            {(calculationsTabs || []).map((tab) => (
                                <div
                                    key={tab.id}
                                    className={`group flex items-center gap-1 px-3 py-1.5 rounded-t-lg border-b-2 transition-colors ${
                                        activeTabId === tab.id
                                            ? 'bg-slate-100 border-indigo-500 text-slate-900'
                                            : 'bg-slate-50 border-transparent text-slate-600 hover:bg-slate-100 hover:text-slate-900'
                                    }`}
                                >
                                    <input
                                        type="text"
                                        value={tab.name}
                                        onChange={(e) => updateTab(tab.id, e.target.value)}
                                        onClick={() => setActiveTabId(tab.id)}
                                        className="bg-transparent border-none outline-none text-sm font-medium w-20 min-w-[60px] max-w-[120px]"
                                        style={{ width: `${Math.max(60, tab.name.length * 8)}px` }}
                                    />
                                    {(calculationsTabs || []).length > 1 && (
                                        <button
                                            onClick={(e) => {
                                                e.stopPropagation()
                                                removeTab(tab.id)
                                            }}
                                            className="p-0.5 text-slate-400 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                                        >
                                            <Trash2 className="w-3 h-3" />
                                        </button>
                                    )}
                                </div>
                            ))}
                            <button
                                onClick={addTab}
                                className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-slate-100 rounded transition-colors"
                                title="Add new tab"
                            >
                                <Plus className="w-4 h-4" />
                            </button>
                        </div>

                        <div className="flex-1 p-6 overflow-y-auto">
                        {(() => {
                            // Get first tab id for backwards compatibility (calcs without tabId go to first tab)
                            const firstTabId = (calculationsTabs || [])[0]?.id
                            const isFirstTab = activeTabId === firstTabId

                            // Filter calculations - include those without tabId if we're on the first tab
                            const tabCalcs = (calculations || []).filter(c =>
                                c.tabId === activeTabId || (isFirstTab && !c.tabId)
                            )
                            const tabGroups = (calculationsGroups || []).filter(g =>
                                g.tabId === activeTabId || (isFirstTab && !g.tabId)
                            )

                            if (tabCalcs.length === 0 && tabGroups.length === 0) {
                                return (
                                    <div className="text-center py-12 text-slate-500">
                                        <div className="text-4xl mb-3">∑</div>
                                        <p className="text-sm">No calculations in this tab yet</p>
                                        <p className="text-xs mt-1">Click "Add Calculation" to create your first formula</p>
                                    </div>
                                )
                            }
                            return (
                            <div className="space-y-6">
                                {tabGroups.map((group) => {
                                    const groupCalcs = tabCalcs.filter(c => c.groupId === group.id)
                                    const isCollapsed = collapsedCalculationsGroups?.has(group.id)

                                    return (
                                        <div key={group.id} className="border border-slate-200 rounded-lg overflow-hidden">
                                            {/* Group Header */}
                                            <div
                                                className="flex items-center justify-between px-4 py-3 bg-slate-100 border-b border-slate-200 cursor-pointer hover:bg-slate-150"
                                                onClick={() => toggleGroupCollapse(group.id)}
                                            >
                                                <div className="flex items-center gap-3">
                                                    {isCollapsed ? (
                                                        <ChevronRight className="w-4 h-4 text-slate-500" />
                                                    ) : (
                                                        <ChevronDown className="w-4 h-4 text-slate-500" />
                                                    )}
                                                    <input
                                                        type="text"
                                                        value={group.name}
                                                        onClick={(e) => e.stopPropagation()}
                                                        onChange={(e) => updateCalculationsGroup(group.id, 'name', e.target.value)}
                                                        className="text-sm font-semibold text-slate-900 bg-transparent border-none focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:bg-white rounded px-1"
                                                    />
                                                    <span className="text-xs text-slate-500">({groupCalcs.length} calculations)</span>
                                                </div>
                                                <div className="flex items-center gap-2">
                                                    <button
                                                        onClick={(e) => {
                                                            e.stopPropagation()
                                                            addCalculation(group.id)
                                                        }}
                                                        className="p-1.5 text-slate-500 hover:text-indigo-600 hover:bg-indigo-50 rounded transition-colors"
                                                        title="Add calculation to this group"
                                                    >
                                                        <Plus className="w-4 h-4" />
                                                    </button>
                                                    {(calculationsGroups || []).length > 1 && (
                                                        <button
                                                            onClick={(e) => {
                                                                e.stopPropagation()
                                                                removeCalculationsGroup(group.id)
                                                            }}
                                                            className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded transition-colors"
                                                            title="Delete group"
                                                        >
                                                            <Trash2 className="w-4 h-4" />
                                                        </button>
                                                    )}
                                                </div>
                                            </div>

                                            {/* Group Content */}
                                            {!isCollapsed && (
                                                <div className="p-4 space-y-3">
                                                    {groupCalcs.length === 0 ? (
                                                        <div className="text-center py-6 text-slate-400 text-sm">
                                                            No calculations in this group
                                                        </div>
                                                    ) : (
                                                        groupCalcs.map((calc) => {
                                                            const calcIndex = calcIndexMap.get(calc.id) - 1
                                                            const isSelected = selectedCalculationId === calc.id
                                                            const isDragging = calcDraggedIndex === calcIndex
                                                            const isDragOver = calcDragOverIndex === calcIndex

                                                            return (
                                                                <div
                                                                    key={calc.id}
                                                                    draggable
                                                                    onDragStart={(e) => handleCalcDragStart(e, calcIndex)}
                                                                    onDragOver={(e) => handleCalcDragOver(e, calcIndex)}
                                                                    onDrop={(e) => handleCalcDrop(e, calcIndex)}
                                                                    onDragEnd={handleCalcDragEnd}
                                                                    onClick={() => setSelectedCalculationId(isSelected ? null : calc.id)}
                                                                    className={`border rounded-lg p-4 bg-white transition-colors cursor-pointer ${
                                                                        isSelected
                                                                            ? 'border-indigo-500 ring-2 ring-indigo-200'
                                                                            : 'border-slate-200 hover:border-indigo-300'
                                                                    } ${isDragging ? 'opacity-50' : ''} ${isDragOver ? 'border-t-4 border-t-indigo-500' : ''}`}
                                                                >
                                                                    <div className="flex items-start justify-between gap-4">
                                                                        <div className="flex-1">
                                                                            {/* Label row: Drag Handle | R1 | Name = Expanded Formula */}
                                                                            <div className="flex items-center gap-2 mb-2">
                                                                                <div
                                                                                    className="p-1 rounded hover:bg-slate-200 cursor-grab active:cursor-grabbing transition-colors"
                                                                                    onMouseDown={(e) => e.stopPropagation()}
                                                                                >
                                                                                    <GripVertical className="w-5 h-5 text-slate-400 hover:text-slate-600" />
                                                                                </div>
                                                                                <span className="text-xs px-1.5 py-0.5 rounded font-medium text-rose-600 bg-rose-100">
                                                                                    R{calcIndexMap.get(calc.id)}
                                                                                </span>
                                                                                <input
                                                                                    type="text"
                                                                                    value={calc.name}
                                                                                    onClick={(e) => e.stopPropagation()}
                                                                                    onChange={(e) => updateCalculation(calc.id, 'name', e.target.value)}
                                                                                    className="text-sm font-semibold text-slate-900 bg-slate-100 border border-slate-200 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                                                                                    placeholder="Calculation name"
                                                                                />
                                                                                <span className="text-sm text-slate-500">=</span>
                                                                                <span className="text-sm text-slate-600 italic">
                                                                                    {expandFormulaToNames(calc.formula) || 'Enter formula below...'}
                                                                                </span>
                                                                            </div>
                                                                            {/* Formula input row */}
                                                                            <div className="flex items-center gap-2 pl-8">
                                                                                <span className="text-xs text-slate-400 w-14">Formula:</span>
                                                                                <input
                                                                                    type="text"
                                                                                    value={calc.formula}
                                                                                    onClick={(e) => e.stopPropagation()}
                                                                                    onChange={(e) => updateCalculation(calc.id, 'formula', e.target.value)}
                                                                                    className="flex-1 text-sm font-mono text-slate-700 bg-slate-50 border border-slate-200 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                                                                                    placeholder="e.g., V1 * F1 + S1.1"
                                                                                />
                                                                            </div>
                                                                            {/* Preview and Sample Calculation */}
                                                                            {isSelected && calc.formula && (
                                                                                <CalculationPreview
                                                                                    calc={calc}
                                                                                    calcIndex={calcIndexMap.get(calc.id) - 1}
                                                                                    timeline={timeline}
                                                                                    referenceMap={referenceMap}
                                                                                    calculationResults={calculationResults}
                                                                                    error={calculationErrors?.[`R${calcIndexMap.get(calc.id)}`]}
                                                                                />
                                                                            )}
                                                                        </div>
                                                                        <button
                                                                            onClick={(e) => {
                                                                                e.stopPropagation()
                                                                                removeCalculation(calc.id)
                                                                            }}
                                                                            className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded transition-colors"
                                                                        >
                                                                            <Trash2 className="w-4 h-4" />
                                                                        </button>
                                                                    </div>
                                                                </div>
                                                            )
                                                        })
                                                    )}
                                                </div>
                                            )}
                                        </div>
                                    )
                                })}

                                {/* Ungrouped calculations (for backwards compatibility) */}
                                {(() => {
                                    const ungroupedCalcs = tabCalcs.filter(c =>
                                        !c.groupId || !tabGroups.some(g => g.id === c.groupId)
                                    )
                                    if (ungroupedCalcs.length === 0) return null

                                    return (
                                        <div className="border border-slate-200 rounded-lg overflow-hidden">
                                            <div className="px-4 py-3 bg-slate-100 border-b border-slate-200">
                                                <span className="text-sm font-semibold text-slate-700">Ungrouped</span>
                                                <span className="text-xs text-slate-500 ml-2">({ungroupedCalcs.length})</span>
                                            </div>
                                            <div className="p-4 space-y-3">
                                                {ungroupedCalcs.map((calc) => {
                                                    const calcIndex = calcIndexMap.get(calc.id) - 1
                                                    const isSelected = selectedCalculationId === calc.id

                                                    return (
                                                        <div
                                                            key={calc.id}
                                                            onClick={() => setSelectedCalculationId(isSelected ? null : calc.id)}
                                                            className={`border rounded-lg p-4 bg-white transition-colors cursor-pointer ${
                                                                isSelected
                                                                    ? 'border-indigo-500 ring-2 ring-indigo-200'
                                                                    : 'border-slate-200 hover:border-indigo-300'
                                                            }`}
                                                        >
                                                            <div className="flex items-start justify-between gap-4">
                                                                <div className="flex-1">
                                                                    <div className="flex items-center gap-2 mb-2">
                                                                        <span className="text-xs px-1.5 py-0.5 rounded font-medium text-rose-600 bg-rose-100">
                                                                            R{calcIndexMap.get(calc.id)}
                                                                        </span>
                                                                        <input
                                                                            type="text"
                                                                            value={calc.name}
                                                                            onClick={(e) => e.stopPropagation()}
                                                                            onChange={(e) => updateCalculation(calc.id, 'name', e.target.value)}
                                                                            className="text-sm font-semibold text-slate-900 bg-slate-100 border border-slate-200 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                                                                            placeholder="Calculation name"
                                                                        />
                                                                        <span className="text-sm text-slate-500">=</span>
                                                                        <span className="text-sm text-slate-600 italic">
                                                                            {expandFormulaToNames(calc.formula) || 'Enter formula below...'}
                                                                        </span>
                                                                    </div>
                                                                    <div className="flex items-center gap-2 pl-8">
                                                                        <span className="text-xs text-slate-400 w-14">Formula:</span>
                                                                        <input
                                                                            type="text"
                                                                            value={calc.formula}
                                                                            onClick={(e) => e.stopPropagation()}
                                                                            onChange={(e) => updateCalculation(calc.id, 'formula', e.target.value)}
                                                                            className="flex-1 text-sm font-mono text-slate-700 bg-slate-50 border border-slate-200 rounded px-2 py-1 focus:outline-none focus:ring-2 focus:ring-indigo-500"
                                                                            placeholder="e.g., V1 * F1 + S1.1"
                                                                        />
                                                                    </div>
                                                                    {/* Preview and Sample Calculation */}
                                                                    {isSelected && calc.formula && (
                                                                        <CalculationPreview
                                                                            calc={calc}
                                                                            calcIndex={calcIndexMap.get(calc.id) - 1}
                                                                            timeline={timeline}
                                                                            referenceMap={referenceMap}
                                                                            calculationResults={calculationResults}
                                                                            error={calculationErrors?.[`R${calcIndexMap.get(calc.id)}`]}
                                                                        />
                                                                    )}
                                                                </div>
                                                                <button
                                                                    onClick={(e) => {
                                                                        e.stopPropagation()
                                                                        removeCalculation(calc.id)
                                                                    }}
                                                                    className="p-1.5 text-slate-400 hover:text-red-500 hover:bg-red-50 rounded transition-colors"
                                                                >
                                                                    <Trash2 className="w-4 h-4" />
                                                                </button>
                                                            </div>
                                                        </div>
                                                    )
                                                })}
                                            </div>
                                        </div>
                                    )
                                })()}
                            </div>
                            )
                        })()}
                        </div>
                    </div>
                </div>

                {/* Help Text */}
                <div className="px-6 py-4 border-t border-slate-200 bg-slate-50">
                    <div className="flex items-center gap-6 text-xs text-slate-600">
                        <span className="font-medium text-slate-700">Formula syntax:</span>
                        <span><code className="bg-slate-200 px-1.5 py-0.5 rounded">V1 + S1</code> Addition</span>
                        <span><code className="bg-slate-200 px-1.5 py-0.5 rounded">V1 * F1</code> Multiply by flag</span>
                        <span><code className="bg-slate-200 px-1.5 py-0.5 rounded">V1.1 - V1.2</code> Sub-item math</span>
                        <span><code className="bg-slate-200 px-1.5 py-0.5 rounded">R1 + R2</code> Chain calculations</span>
                    </div>
                </div>

                {/* Generated Time Series Preview */}
                {calculations && calculations.length > 0 && (
                    <CalculationsTimeSeriesPreview
                        calculations={calculations}
                        calculationsGroups={calculationsGroups}
                        calculationResults={calculationResults}
                        calculationTypes={calculationTypes}
                        viewHeaders={viewHeaders}
                        viewMode={viewMode}
                        calcIndexMap={calcIndexMap}
                    />
                )}
            </div>
        </main>
    )
}

function CalculationPreview({ calc, calcIndex, timeline, referenceMap, calculationResults, error }) {
    const resultArray = calculationResults[`R${calcIndex + 1}`] || []

    // Show error if present
    if (error) {
        return (
            <div className="mt-3 pt-3 border-t border-slate-100">
                <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
                    <div className="text-sm font-medium text-red-700">Formula Error</div>
                    <div className="text-xs text-red-600 mt-1">{error}</div>
                </div>
            </div>
        )
    }

    // Find first non-zero index to start preview from relevant data
    let startIndex = 0
    for (let i = 0; i < resultArray.length; i++) {
        if (resultArray[i] !== 0) {
            startIndex = i
            break
        }
    }
    const MONTH_NAMES = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    const formatPeriod = (idx) => {
        const year = timeline.year?.[idx]
        const month = timeline.month?.[idx]
        if (year !== undefined && month !== undefined) {
            return `${MONTH_NAMES[month - 1]} ${String(year).slice(-2)}`
        }
        return `P${idx + 1}`
    }
    const periodLabel = formatPeriod(startIndex)

    // Build sample calculation breakdown
    const allRefs = { ...referenceMap, ...calculationResults }
    const sortedRefs = Object.keys(allRefs).sort((a, b) => b.length - a.length)
    let substitutedFormula = calc.formula
    for (const ref of sortedRefs) {
        const value = allRefs[ref]?.[startIndex] ?? 0
        const formattedValue = value.toLocaleString('en-AU', { maximumFractionDigits: 2 })
        const regex = new RegExp(`\\b${ref.replace('.', '\\.')}\\b`, 'g')
        substitutedFormula = substitutedFormula.replace(regex, formattedValue)
    }
    const resultValue = resultArray[startIndex] ?? 0

    const previewCount = Math.min(5, timeline.periods - startIndex)

    return (
        <div className="mt-3 pt-3 border-t border-slate-100">
            {/* Sample Calculation */}
            <div className="mb-3 p-3 bg-slate-50 rounded-lg">
                <div className="text-xs text-slate-500 mb-2">Sample calculation ({periodLabel}):</div>
                <div className="font-mono text-sm space-y-1">
                    <div className="text-slate-600">{calc.formula}</div>
                    <div className="text-slate-500">= {substitutedFormula}</div>
                    <div className="text-rose-600 font-semibold">= {resultValue.toLocaleString('en-AU', { maximumFractionDigits: 2 })}</div>
                </div>
            </div>

            {/* Preview values */}
            <div className="flex items-center gap-2">
                <span className="text-xs text-slate-500 w-16">Preview:</span>
                <div className="flex gap-1">
                    {Array.from({ length: previewCount }).map((_, i) => {
                        const idx = startIndex + i
                        const value = resultArray[idx] ?? 0
                        const pLabel = formatPeriod(idx)
                        return (
                            <div key={idx} className="flex flex-col items-center">
                                <span className="text-[10px] text-slate-400">{pLabel}</span>
                                <span className={`text-xs font-mono px-2 py-1 rounded ${
                                    value === 0 ? 'bg-slate-100 text-slate-400' : 'bg-rose-50 text-rose-700'
                                }`}>
                                    {value.toLocaleString('en-AU', { maximumFractionDigits: 2 })}
                                </span>
                            </div>
                        )
                    })}
                    {timeline.periods > 5 && (
                        <span className="text-xs text-slate-400 self-end pb-1">...</span>
                    )}
                </div>
            </div>
        </div>
    )
}

function CalculationsTimeSeriesPreview({ calculations, calculationsGroups, calculationResults, calculationTypes, viewHeaders, viewMode, calcIndexMap }) {
    const viewModeLabel = viewMode === 'M' ? 'Monthly' :
                          viewMode === 'Q' ? 'Quarterly' :
                          viewMode === 'Y' ? 'Yearly' : 'Financial Year'

    // Calculate grand total across all calculations (only sum flows, not stocks)
    const grandTotalByPeriod = viewHeaders.map((header) => {
        return calculations.reduce((sum, calc) => {
            const calcRef = `R${calcIndexMap.get(calc.id)}`
            const resultArray = calculationResults[calcRef] || []
            const calcType = calculationTypes?.[calcRef] || 'flow'

            // Only include flows in the grand total (stocks shouldn't be summed)
            if (calcType === 'stock') return sum

            if (viewMode === 'M') {
                return sum + (resultArray[header.index] ?? 0)
            } else {
                return sum + getAggregatedValueForArray(resultArray, header.indices || [header.index], calcType)
            }
        }, 0)
    })
    const overallTotal = grandTotalByPeriod.reduce((sum, v) => sum + v, 0)

    return (
        <div className="border-t border-slate-200 pt-4 pb-4 px-6">
            <div className="text-xs font-semibold text-slate-500 uppercase mb-3">
                Generated Time Series Preview ({viewModeLabel})
            </div>
            <div className="overflow-x-auto">
                <table className="text-sm table-fixed">
                    <thead>
                        <tr className="bg-slate-50 border-b border-slate-200">
                            <th className="text-left py-2 px-3 text-xs font-semibold text-slate-500 uppercase w-[240px] min-w-[240px] sticky left-0 z-20 bg-slate-50">
                                Calculation
                            </th>
                            <th className="text-right py-1 px-3 text-xs font-semibold text-slate-500 uppercase w-[96px] min-w-[96px] sticky left-[240px] z-10 bg-slate-50 border-r border-slate-300">
                                Total
                            </th>
                            {viewHeaders.map((header, i) => (
                                <th key={i} className="text-center py-1 px-0 text-[10px] font-medium text-slate-500 min-w-[55px] w-[55px]">
                                    {header.label}
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {/* Grouped calculations */}
                        {(calculationsGroups || []).map((group) => {
                            const groupCalcs = calculations.filter(c => c.groupId === group.id)
                            if (groupCalcs.length === 0) return null

                            // Calculate group subtotal
                            const groupSubtotalByPeriod = viewHeaders.map((header) => {
                                return groupCalcs.reduce((sum, calc) => {
                                    const calcRef = `R${calcIndexMap.get(calc.id)}`
                                    const resultArray = calculationResults[calcRef] || []
                                    const calcType = calculationTypes?.[calcRef] || 'flow'
                                    if (calcType === 'stock') return sum
                                    if (viewMode === 'M') {
                                        return sum + (resultArray[header.index] ?? 0)
                                    } else {
                                        return sum + getAggregatedValueForArray(resultArray, header.indices || [header.index], calcType)
                                    }
                                }, 0)
                            })
                            const groupTotal = groupSubtotalByPeriod.reduce((sum, v) => sum + v, 0)

                            return (
                                <React.Fragment key={group.id}>
                                    {/* Group header row */}
                                    <tr className="bg-rose-50 border-b border-rose-200">
                                        <td className="py-1.5 px-3 text-xs font-semibold text-rose-800 w-[240px] min-w-[240px] sticky left-0 z-20 bg-rose-50">
                                            {group.name}
                                        </td>
                                        <td className="py-1.5 px-3 text-right text-xs font-bold text-rose-900 w-[96px] min-w-[96px] sticky left-[240px] z-10 bg-rose-50 border-r border-rose-200">
                                            {groupTotal.toLocaleString('en-US', { maximumFractionDigits: 2 })}
                                        </td>
                                        {groupSubtotalByPeriod.map((val, i) => (
                                            <td key={i} className="py-1 px-0.5 text-right text-[11px] font-semibold text-rose-700 min-w-[55px] w-[55px] border-r border-rose-100">
                                                {val !== 0 ? val.toLocaleString('en-US', { maximumFractionDigits: 1 }) : ''}
                                            </td>
                                        ))}
                                    </tr>
                                    {/* Individual calculation rows */}
                                    {groupCalcs.map((calc) => {
                                        const calcRef = `R${calcIndexMap.get(calc.id)}`
                                        const resultArray = calculationResults[calcRef] || []
                                        const calcType = calculationTypes?.[calcRef] || 'flow'

                                        const periodValues = viewHeaders.map((header) => {
                                            if (viewMode === 'M') {
                                                return resultArray[header.index] ?? 0
                                            } else {
                                                return getAggregatedValueForArray(resultArray, header.indices || [header.index], calcType)
                                            }
                                        })
                                        const total = calcType === 'stock'
                                            ? periodValues[periodValues.length - 1] || 0
                                            : periodValues.reduce((sum, v) => sum + v, 0)

                                        return (
                                            <tr key={calc.id} className="border-b border-slate-100 hover:bg-rose-50/30">
                                                <td className="py-1 px-3 text-xs text-slate-700 w-[240px] min-w-[240px] sticky left-0 z-20 bg-white pl-6">
                                                    <div className="flex items-center gap-2">
                                                        <span className="text-xs px-1.5 py-0.5 rounded font-medium text-rose-600 bg-rose-100">
                                                            {calcRef}
                                                        </span>
                                                        <span className="truncate">{calc.name}</span>
                                                        <span className={`text-[10px] px-1 py-0.5 rounded ${
                                                            calcType === 'flow'
                                                                ? 'text-emerald-600 bg-emerald-50'
                                                                : 'text-slate-500 bg-slate-100'
                                                        }`}>
                                                            {calcType}
                                                        </span>
                                                    </div>
                                                </td>
                                                <td className="py-1 px-3 text-right text-xs font-medium text-slate-900 w-[96px] min-w-[96px] sticky left-[240px] z-10 bg-white border-r border-slate-200">
                                                    {total.toLocaleString('en-US', { maximumFractionDigits: 2 })}
                                                </td>
                                                {periodValues.map((val, i) => (
                                                    <td key={i} className="py-1 px-0.5 text-right text-[11px] text-slate-600 min-w-[55px] w-[55px] border-r border-slate-100">
                                                        {val !== 0 ? val.toLocaleString('en-US', { maximumFractionDigits: 2 }) : ''}
                                                    </td>
                                                ))}
                                            </tr>
                                        )
                                    })}
                                </React.Fragment>
                            )
                        })}

                        {/* Ungrouped calculations */}
                        {(() => {
                            const ungroupedCalcs = calculations.filter(c =>
                                !c.groupId || !(calculationsGroups || []).some(g => g.id === c.groupId)
                            )
                            if (ungroupedCalcs.length === 0) return null

                            return ungroupedCalcs.map((calc) => {
                                const calcRef = `R${calcIndexMap.get(calc.id)}`
                                const resultArray = calculationResults[calcRef] || []
                                const calcType = calculationTypes?.[calcRef] || 'flow'

                                const periodValues = viewHeaders.map((header) => {
                                    if (viewMode === 'M') {
                                        return resultArray[header.index] ?? 0
                                    } else {
                                        return getAggregatedValueForArray(resultArray, header.indices || [header.index], calcType)
                                    }
                                })
                                const total = calcType === 'stock'
                                    ? periodValues[periodValues.length - 1] || 0
                                    : periodValues.reduce((sum, v) => sum + v, 0)

                                return (
                                    <tr key={calc.id} className="border-b border-slate-100 hover:bg-rose-50/30">
                                        <td className="py-1 px-3 text-xs text-slate-700 w-[240px] min-w-[240px] sticky left-0 z-20 bg-white">
                                            <div className="flex items-center gap-2">
                                                <span className="text-xs px-1.5 py-0.5 rounded font-medium text-rose-600 bg-rose-100">
                                                    {calcRef}
                                                </span>
                                                <span className="truncate">{calc.name}</span>
                                                <span className={`text-[10px] px-1 py-0.5 rounded ${
                                                    calcType === 'flow'
                                                        ? 'text-emerald-600 bg-emerald-50'
                                                        : 'text-slate-500 bg-slate-100'
                                                }`}>
                                                    {calcType}
                                                </span>
                                            </div>
                                        </td>
                                        <td className="py-1 px-3 text-right text-xs font-medium text-slate-900 w-[96px] min-w-[96px] sticky left-[240px] z-10 bg-white border-r border-slate-200">
                                            {total.toLocaleString('en-US', { maximumFractionDigits: 2 })}
                                        </td>
                                        {periodValues.map((val, i) => (
                                            <td key={i} className="py-1 px-0.5 text-right text-[11px] text-slate-600 min-w-[55px] w-[55px] border-r border-slate-100">
                                                {val !== 0 ? val.toLocaleString('en-US', { maximumFractionDigits: 2 }) : ''}
                                            </td>
                                        ))}
                                    </tr>
                                )
                            })
                        })()}

                        {/* Grand Total row */}
                        <tr className="bg-slate-100">
                            <td className="py-1.5 px-3 text-xs font-semibold text-slate-700 w-[240px] min-w-[240px] sticky left-0 z-20 bg-slate-100">
                                Grand Total
                            </td>
                            <td className="py-1.5 px-3 text-right text-xs font-bold text-slate-900 w-[96px] min-w-[96px] sticky left-[240px] z-10 bg-slate-100 border-r border-slate-300">
                                {overallTotal.toLocaleString('en-US', { maximumFractionDigits: 2 })}
                            </td>
                            {grandTotalByPeriod.map((val, i) => (
                                <td key={i} className="py-1 px-0.5 text-right text-[11px] font-semibold text-slate-700 min-w-[55px] w-[55px] border-r border-slate-100">
                                    {val !== 0 ? val.toLocaleString('en-US', { maximumFractionDigits: 1 }) : ''}
                                </td>
                            ))}
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    )
}
