'use client'

import { useRef, useEffect, useState, useCallback } from 'react'
import { ChevronDown, ChevronRight, Plus } from 'lucide-react'
import ExcelInputs from '@/components/inputs/ExcelInputs'
import IndicesSection from '@/components/inputs/IndicesSection'
import { useDashboard } from '../context/DashboardContext'

export default function InputsPage() {
    const {
        viewMode,
        inputsEditMode,
        appState,
        setters,
        handlers,
        derived
    } = useDashboard()

    const {
        config,
        showIndices,
        keyPeriods,
        inputGlass,
        indices,
        inputGlassGroups,
        collapsedInputGlassGroups
    } = appState

    const { timeline, autoGeneratedIndexations } = derived

    const {
        setShowIndices,
        setCollapsedInputGlassGroups
    } = setters

    const {
        addInputGlassGroup,
        updateInputGlassGroup,
        removeInputGlassGroup,
        addInputGlass,
        updateInputGlass,
        removeInputGlass,
        addInputGlassSubgroup,
        updateInputGlassSubgroup,
        removeInputGlassSubgroup,
        addIndex,
        updateIndex,
        removeIndex
    } = handlers

    // Track which group to scroll to after adding
    const [scrollToGroupId, setScrollToGroupId] = useState(null)
    const stickyHeaderRef = useRef(null)

    const handleAddGroup = useCallback(() => {
        const newId = addInputGlassGroup()
        setScrollToGroupId(newId)
    }, [addInputGlassGroup])

    return (
        <>
            {/* Inputs Section */}
            <section className="max-w-[1800px] mx-auto px-6 pt-6">
                {/* Sticky header - outside overflow-hidden so sticky works */}
                <div
                    ref={stickyHeaderRef}
                    className="bg-slate-50 border border-slate-200 border-b-slate-200 rounded-t-xl px-6 py-4 sticky top-[176px] z-40 shadow-lg"
                >
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <h2 className="text-lg font-semibold text-slate-900">Inputs</h2>
                            <span className="text-xs text-slate-600">Values by period</span>
                        </div>
                        {inputsEditMode && (
                            <button
                                onClick={handleAddGroup}
                                className="flex items-center gap-1.5 px-4 py-2 text-sm bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                            >
                                <Plus className="w-4 h-4" />
                                Add Group
                            </button>
                        )}
                    </div>
                </div>
                {/* Card body */}
                <div className="bg-white backdrop-blur border border-slate-200 border-t-0 rounded-b-xl overflow-hidden shadow-lg">
                    <div className="p-6">
                        <ExcelInputs
                            groups={inputGlassGroups}
                            inputs={inputGlass}
                            config={config}
                            keyPeriods={keyPeriods}
                            viewMode={viewMode}
                            inputsEditMode={inputsEditMode}
                            onUpdateGroup={updateInputGlassGroup}
                            onRemoveGroup={removeInputGlassGroup}
                            onAddInput={addInputGlass}
                            onUpdateInput={updateInputGlass}
                            onRemoveInput={removeInputGlass}
                            onAddSubgroup={addInputGlassSubgroup}
                            onUpdateSubgroup={updateInputGlassSubgroup}
                            onRemoveSubgroup={removeInputGlassSubgroup}
                            collapsedGroups={collapsedInputGlassGroups}
                            setCollapsedGroups={setCollapsedInputGlassGroups}
                            scrollToGroupId={scrollToGroupId}
                            onScrollComplete={() => setScrollToGroupId(null)}
                        />
                    </div>
                </div>
            </section>

            {/* Indices Section */}
            <section className="max-w-[1800px] mx-auto px-6 py-6">
                <div className="bg-white backdrop-blur border border-slate-200 rounded-xl overflow-hidden shadow-lg mb-6">
                    <div className="bg-slate-50 border-b border-slate-200 px-6 py-4">
                        <button
                            onClick={() => setShowIndices(!showIndices)}
                            className="flex items-center justify-between w-full text-left"
                        >
                            <div className="flex items-center gap-3">
                                {showIndices ? (
                                    <ChevronDown className="w-5 h-5 text-slate-600" />
                                ) : (
                                    <ChevronRight className="w-5 h-5 text-slate-600" />
                                )}
                                <h2 className="text-lg font-semibold text-slate-900">Indices</h2>
                                <span className="text-xs text-slate-600">Indexation time series</span>
                            </div>
                        </button>
                    </div>

                    {showIndices && (
                        <div className="p-6">
                            <IndicesSection
                                indices={indices}
                                config={config}
                                inputsEditMode={inputsEditMode}
                                autoGeneratedIndexations={autoGeneratedIndexations}
                                timeline={timeline}
                                viewMode={viewMode}
                                onAddIndex={addIndex}
                                onUpdateIndex={updateIndex}
                                onRemoveIndex={removeIndex}
                            />
                        </div>
                    )}
                </div>
            </section>

        </>
    )
}
