import React, { useMemo } from 'react'
import { Plus, Trash2 } from 'lucide-react'
import { theme, cn } from './theme'

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

function formatPeriodLabel(year, month, viewMode, config) {
    if (viewMode === 'FY') {
        return `FY${year + 1}`
    }
    if (viewMode === 'Y') return String(year)
    if (viewMode === 'Q') {
        const q = Math.ceil(month / 3)
        return `Q${q} ${String(year).slice(2)}`
    }
    return `${MONTHS[month - 1]} ${String(year).slice(2)}`
}

export default function IndicesSection({
    indices,
    config,
    inputsEditMode = true,
    autoGeneratedIndexations,
    timeline,
    viewMode = 'Y',
    onAddIndex,
    onUpdateIndex,
    onRemoveIndex
}) {
    // Generate year options
    const startYear = (config?.startYear || 2024) - 5
    const endYear = config?.endYear || 2030
    const years = []
    for (let y = startYear; y <= endYear; y++) {
        years.push(y)
    }

    // View mode: show generated preview
    if (!inputsEditMode) {
        return (
            <IndicesPreview
                indices={indices}
                autoGeneratedIndexations={autoGeneratedIndexations}
                timeline={timeline}
                viewMode={viewMode}
                config={config}
            />
        )
    }

    // Edit mode: show editable table
    return (
        <div className="space-y-4">
            <div className="bg-white rounded-lg border border-slate-300 overflow-hidden">
                <table className="w-full">
                    <thead className={cn(theme.bg.sectionHeader, 'border-b', theme.border.light)}>
                        <tr>
                            <th className={cn('px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider', theme.text.secondary)}>
                                Name
                            </th>
                            <th className={cn('px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider', theme.text.secondary)}>
                                Start Date (MM/YYYY)
                            </th>
                            <th className={cn('px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider', theme.text.secondary)}>
                                Rate (%)
                            </th>
                            <th className={cn('px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider', theme.text.secondary)}>
                                Period
                            </th>
                            <th className={cn('px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider', theme.text.secondary)}>
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {indices.map((index) => (
                            <tr
                                key={index.id}
                                className="border-b border-slate-200 hover:bg-slate-50"
                            >
                                <td className="px-4 py-3">
                                    <input
                                        type="text"
                                        value={index.name}
                                        onChange={(e) => onUpdateIndex(index.id, 'name', e.target.value)}
                                        className="border border-slate-300 rounded px-2 py-1 text-sm w-full bg-white text-slate-900 focus:border-indigo-500 focus:outline-none"
                                        placeholder="Index Name"
                                    />
                                </td>
                                <td className="px-4 py-3">
                                    <div className="flex items-center gap-1">
                                        <select
                                            value={index.indexationStartMonth || 1}
                                            onChange={(e) => onUpdateIndex(index.id, 'indexationStartMonth', parseInt(e.target.value))}
                                            className="border border-slate-300 rounded px-2 py-1 text-sm bg-white text-slate-900 focus:border-indigo-500 focus:outline-none"
                                        >
                                            {MONTHS.map((month, i) => (
                                                <option key={i} value={i + 1}>{month}</option>
                                            ))}
                                        </select>
                                        <span className="text-slate-400">/</span>
                                        <select
                                            value={index.indexationStartYear || startYear}
                                            onChange={(e) => onUpdateIndex(index.id, 'indexationStartYear', parseInt(e.target.value))}
                                            className="border border-slate-300 rounded px-2 py-1 text-sm bg-white text-slate-900 focus:border-indigo-500 focus:outline-none"
                                        >
                                            {years.map(year => (
                                                <option key={year} value={year}>{year}</option>
                                            ))}
                                        </select>
                                    </div>
                                </td>
                                <td className="px-4 py-3">
                                    <input
                                        type="number"
                                        step="0.1"
                                        value={index.indexationRate}
                                        onChange={(e) => onUpdateIndex(index.id, 'indexationRate', parseFloat(e.target.value) || 0)}
                                        className="border border-slate-300 rounded px-2 py-1 text-sm text-right w-24 bg-white text-slate-900 focus:border-indigo-500 focus:outline-none [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none"
                                        placeholder="0"
                                    />
                                </td>
                                <td className="px-4 py-3">
                                    <select
                                        value={index.indexationPeriod || 'annual'}
                                        onChange={(e) => onUpdateIndex(index.id, 'indexationPeriod', e.target.value)}
                                        className="border border-slate-300 rounded px-2 py-1 text-sm bg-white text-slate-900 focus:border-indigo-500 focus:outline-none"
                                    >
                                        <option value="annual">Annual</option>
                                        <option value="monthly">Monthly</option>
                                    </select>
                                </td>
                                <td className="px-4 py-3">
                                    <button
                                        onClick={() => onRemoveIndex(index.id)}
                                        className="p-1.5 text-red-600 hover:text-red-700 hover:bg-red-50 rounded transition-colors"
                                        title="Remove index"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            <div className="flex justify-start">
                <button
                    onClick={onAddIndex}
                    className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg transition-colors"
                >
                    <Plus className="w-4 h-4" />
                    Add Index
                </button>
            </div>
        </div>
    )
}

function IndicesPreview({ indices, autoGeneratedIndexations, timeline, viewMode, config }) {
    // Build period headers based on viewMode
    const previewData = useMemo(() => {
        if (!timeline || !timeline.periods) return { periods: [], indexRows: [] }

        const totalMonths = timeline.periods
        const monthArr = timeline.month
        const yearArr = timeline.year
        const fyStartMonth = config?.fyStartMonth || 7

        // Group monthly periods into viewMode buckets
        const buckets = []
        let currentBucket = null

        for (let i = 0; i < totalMonths; i++) {
            const y = yearArr[i]
            const m = monthArr[i]
            let bucketKey

            if (viewMode === 'FY') {
                const fy = m < fyStartMonth ? y - 1 : y
                bucketKey = `FY${fy}`
            } else if (viewMode === 'Y') {
                bucketKey = `Y${y}`
            } else if (viewMode === 'Q') {
                const q = Math.ceil(m / 3)
                bucketKey = `Q${q}_${y}`
            } else {
                bucketKey = `M${m}_${y}`
            }

            if (!currentBucket || currentBucket.key !== bucketKey) {
                currentBucket = { key: bucketKey, year: y, month: m, indices: [] }
                buckets.push(currentBucket)
            }
            currentBucket.indices.push(i)
        }

        // For each index, get the last value in each bucket (stock/level value)
        const indexRows = indices.map(index => {
            const indexData = autoGeneratedIndexations?.[`index_${index.id}`]
            const arr = indexData?.array || []

            const values = buckets.map(bucket => {
                const lastIdx = bucket.indices[bucket.indices.length - 1]
                return arr[lastIdx] ?? 0
            })

            return {
                id: index.id,
                name: index.name,
                rate: index.indexationRate,
                values
            }
        })

        const periods = buckets.map(b => ({ year: b.year, month: b.month }))

        return { periods, indexRows }
    }, [indices, autoGeneratedIndexations, timeline, viewMode, config])

    const { periods, indexRows } = previewData

    const viewModeLabel = viewMode === 'M' ? 'Monthly' :
                          viewMode === 'Q' ? 'Quarterly' :
                          viewMode === 'Y' ? 'Yearly' : 'Financial Year'

    return (
        <div>
            <div className="text-xs font-semibold text-slate-500 uppercase mb-2 px-3">
                Indexation Preview ({viewModeLabel})
            </div>
            <div className="overflow-x-auto">
                <table className="text-sm table-fixed">
                    <thead>
                        <tr className="bg-slate-50 border-b border-slate-200">
                            <th className="text-left py-2 px-3 text-xs font-semibold text-slate-500 uppercase w-[192px] min-w-[192px] max-w-[192px] sticky left-0 z-20 bg-slate-50">
                                Index
                            </th>
                            <th className="text-right py-1 px-3 text-xs font-semibold text-slate-500 uppercase w-[72px] min-w-[72px] max-w-[72px] sticky left-[192px] z-10 bg-slate-50 border-r border-slate-300">
                                Rate
                            </th>
                            {periods.map((p, i) => (
                                <th key={i} className="text-center py-1 px-0 text-[10px] font-medium text-slate-500 min-w-[55px] w-[55px]">
                                    {formatPeriodLabel(p.year, p.month, viewMode, config)}
                                </th>
                            ))}
                        </tr>
                    </thead>
                    <tbody>
                        {indexRows.map(row => (
                            <tr key={row.id} className="border-b border-slate-100 hover:bg-blue-50/30">
                                <td className="py-1 px-3 text-xs text-slate-700 w-[192px] min-w-[192px] max-w-[192px] sticky left-0 z-20 bg-white">
                                    {row.name}
                                </td>
                                <td className="py-1 px-3 text-right text-xs font-medium text-slate-900 w-[72px] min-w-[72px] max-w-[72px] sticky left-[192px] z-10 bg-white border-r border-slate-200">
                                    {row.rate}%
                                </td>
                                {row.values.map((val, i) => (
                                    <td key={i} className="py-1 px-0.5 text-right text-[11px] text-slate-600 min-w-[55px] w-[55px] border-r border-slate-100">
                                        {val !== 0 ? val.toFixed(4) : ''}
                                    </td>
                                ))}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    )
}
